version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      # Replace with your actual MongoDB URI
      MONGO_URI: "mongodb+srv://amit:AFft5384CYsmPPG5@sustainable-product.obwtyr6.mongodb.net/?retryWrites=true&w=majority&appName=sustainable-product"
      JWT_SECRET: "iuschuisdchdsjcsijosi"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: